### ISSUE TITLE
Backend: adjust arithmetics

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#160]

**Comment by ChrisKujawa** [comment]
<pre>
$ java Main
Exception in thread "main" java.lang.VerifyError: Local variable table overflow
Exception Details:
  Location:
    Main.main([Ljava/lang/String;)V @37: istore_1
  Reason:
    Local index 1 is invalid
  Bytecode:
    0000000: b200 4512 47b8 003a b600 42b2 0045 1248
    0000010: b800 3ab6 0042 b200 45b2 0045 b600 41c0
    0000020: 0027 b600 3b3c b200 45b6 0041 c000 27b6
    0000030: 003b 1b64 b800 3ab6 0042 b200 4512 49b8
    0000040: 003a b600 42b2 0045 b200 45b6 0041 c000
    0000050: 27b6 003b 3cb2 0045 b600 41c0 0027 b600
    0000060: 3b1b 60b8 003a b600 42b2 0045 124a b800
    0000070: 3ab6 0042 b200 45b2 0045 b600 41c0 0027
    0000080: b600 3b3c b200 45b6 0041 c000 27b6 003b
    0000090: 1b68 b800 3ab6 0042 b200 4512 48b8 003a
    00000a0: b600 42b2 0045 b200 45b6 0041 c000 27b6
    00000b0: 003b 3cb2 0045 b600 41c0 0027 b600 3b1b
    00000c0: 6cb8 003a b600 42b2 0045 124a b800 3ab6
    00000d0: 0042 b200 45b2 0045 b600 41c0 0027 b600
    00000e0: 3b3c b200 45b6 0041 c000 27b6 003b 1b70
    00000f0: b800 3ab6 0042 b1                      
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
        at java.lang.Class.getMethod0(Class.java:2813)
        at java.lang.Class.getMethod(Class.java:1663)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
</pre>

problem kam durch testen von: Tests/test-cases2/calculate.txt

**Comment by vincentbohlen** [comment]
done.
