### ISSUE TITLE
fix bug size of string

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#165]
<pre>

$ java Main
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    Main.main([Ljava/lang/String;)V @14: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/String'
  Current Frame:
    bci: @14
    flags: { }
    locals: { '[Ljava/lang/String;' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: b200 4512 48b6 0042 b200 45b6 0041 b600
    0000010: 3fb2 0044 b200 45b6 0041 b600 43b6 0039
    0000020: b1                                     

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
        at java.lang.Class.getMethod0(Class.java:2813)
        at java.lang.Class.getMethod(Class.java:1663)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
</pre>

Test/test-cases2/size.txt

**Comment by vincentbohlen** [comment]
Scheint zu funktionieren. War wohl noch nicht ganz fertig, als das issue erstellt wurde.
