### ISSUE TITLE
fix bug multicut

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#166]
<pre>
$ java Main
Exception in thread "main" java.lang.VerifyError: Local variable table overflow
Exception Details:
  Location:
    Main.main([Ljava/lang/String;)V @44: astore_2
  Reason:
    Local index 2 is invalid
  Bytecode:
    0000000: b200 4512 48b6 0042 b200 4512 49b8 003a
    0000010: b600 42b2 0045 b200 45b6 0041 c000 27b6
    0000020: 003b 3cb2 0045 b200 45b6 0041 4db2 0045
    0000030: 2cb6 0043 031b b600 3db6 0042 b200 452c
    0000040: b600 431b b600 3eb6 0042 b200 4512 4ab8
    0000050: 003a b600 42b2 0045 b200 45b6 0041 c000
    0000060: 27b6 003b 3cb2 0045 b200 45b6 0041 4db2
    0000070: 0045 2cb6 0043 031b b600 3db6 0042 b200
    0000080: 452c b600 431b b600 3eb6 0042 b200 4512
    0000090: 4bb8 003a b600 42b2 0045 b200 45b6 0041
    00000a0: c000 27b6 003b 3cb2 0045 b200 45b6 0041
    00000b0: 4db2 0045 2cb6 0043 031b b600 3db6 0042
    00000c0: b200 452c b600 431b b600 3eb6 0042 b200
    00000d0: 4512 4cb8 003a b600 42b2 0045 b200 45b6
    00000e0: 0041 c000 27b6 003b 3cb2 0045 b200 45b6
    00000f0: 0041 4db2 0045 2cb6 0043 031b b600 3db6
    0000100: 0042 b200 452c b600 431b b600 3eb6 0042
    0000110: b200 44b2 0045 b600 41b6 0043 b600 39b1
    0000120:                                        

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2570)
        at java.lang.Class.getMethod0(Class.java:2813)
        at java.lang.Class.getMethod(Class.java:1663)
        at sun.launcher.LauncherHelper.getMainMethod(LauncherHelper.java:494)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:486)
[zelldon@zelldon-arch io]$ java Main
</pre>

Test/test-cases2/multicut.txt

**Comment by vincentbohlen** [comment]
bug fixed
