### ISSUE TITLE
Lambda.class

### ISSUE THREAD

**Issue by mbaeten** [ccebinger/SWPSoSe14#229]
1. Bitte Namen und Pfad für die Lambda.class anhand von -o bestimmen, damit die im selben Ordner landen: Env.getDstClassfile() & Dateinamen ersetzen:
   
   <pre>
   -o some/random/path/out.class
   => some/random/path/out_lambda.class (brauch ich fürs testen)
   </pre>
2. erzeugt der Kram log files "abrt_checker_xxxxxxx.log"
   
   <pre>
   Uncaught java.lang.ClassNotFoundException exception in thread "main" in a method java.lang.ClassLoader.loadClass() with signature (Ljava/lang/String;Z)Ljava/lang/Class;
   Exception in thread "main" java.lang.ClassNotFoundException: pushconst_cpp.classcppCpp
   at java.net.URLClassLoader$1.run(URLClassLoader.java:366) [jar:file:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.3.0.fc20.x86_64/jre/lib/rt.jar!/java/net/URLClassLoader$1.class]
   at java.net.URLClassLoader$1.run(URLClassLoader.java:355) [jar:file:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.3.0.fc20.x86_64/jre/lib/rt.jar!/java/net/URLClassLoader$1.class]
   at java.security.AccessController.doPrivileged(Native Method) [jar:file:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.3.0.fc20.x86_64/jre/lib/rt.jar!/java/security/AccessController.class]
   at java.net.URLClassLoader.findClass(URLClassLoader.java:354) [jar:file:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.3.0.fc20.x86_64/jre/lib/rt.jar!/java/net/URLClassLoader.class]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:425) [jar:file:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.3.0.fc20.x86_64/jre/lib/rt.jar!/java/lang/ClassLoader.class]
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) [jar:file:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.3.0.fc20.x86_64/jre/lib/rt.jar!/sun/misc/Launcher$AppClassLoader.class]
   at java.lang.ClassLoader.loadClass(ClassLoader.java:358) [jar:file:/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.60-2.4.3.0.fc20.x86_64/jre/lib/rt.jar!/java/lang/ClassLoader.class]
   </pre>

**Comment by ChrisKujawa** [comment]
Ja naja hab ja nich gesagt das ich schon fertig bin oder ^^ aber jo
Btw: 
Was zur hoelle soll das sein ? (2. Zeile)

<pre>
pushconst_cpp.classcppCpp
</pre>

**Comment by mbaeten** [comment]
Ne is alles kein Drama, stört nur grad beim Testing ;D
kA was das ist oder wo's herkommt... Wichtig ist mir gerade eig nur das mit dem Dateipfad/namen

**Comment by ChrisKujawa** [comment]
Wie sieht denn dein Call aus? Lambda sollte gar nicht stoeren da es noch gar nicht in der Main eingebunden ist :)

**Comment by mbaeten** [comment]
Kompilieren

<pre>
../jail/projekt-compiler/Debug/jail -q -i ../jail/projekt-compiler/test/multiCharCommand/constant/pushconst.rail -o tmp/pushconst_cpp.classcppCpp.class
</pre>

Ausführen

<pre>
java -XX:-UseSplitVerifier -cp tmp/ pushconst_cpp.classcppCpp
</pre>

**Comment by mbaeten** [comment]
huch ja ok ich sehs grad selbst... _facepalm_

**Comment by ChrisKujawa** [comment]
Hehe alles klar

**Comment by mbaeten** [comment]
break; vergessen in nem switchblock... schon peinlich ;D Jetzt erzeugt er immerhin keine komischen log files mehr, sondern nurnoch eine Lambda.class im falschen Ordner

**Comment by ChrisKujawa** [comment]
wieder ein grund warum switch scheisse is :D

**Comment by mbaeten** [comment]
macht er doch noch ^^ Hier mal ein Beispiel, aber das ist dir dann ja sowieso bewusst...

<pre>
Uncaught java.lang.ClassCastException exception in thread "main" in a method crash_greater_cppCpp.main() with signature ([Ljava/lang/String;)V
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
    at crash_greater_cppCpp.main(Unknown Source) [file:/home/miro/repos/xTesting/tmp/crash_greater_cppCpp.class]
</pre>

**Comment by ChrisKujawa** [comment]
Ja und was sagt dir die Exception ^^ also entweder is da nen Fehler im Greater d.h. neues Ticket dafuer oder das Testfile is falsch und vergleicht Strings auf greater? 

Aber hat ja nix mit Lambda zutun deshalb mach ich das mal zu

**Comment by mbaeten** [comment]
das ist sinn und zweck von test files ;)
Hast du den dateinamen/pfad angepasst? das muss so oder so gemacht werden

**Comment by ChrisKujawa** [comment]
Naja der Sinn was zu testen ja klar, aber wenn mir ne Ausgabe gibts dann kann ja sonst wat sein wenn ik die Eingabe net kenne ^^ 
Also Ticket auf fuer Greater mit Testfile (Eingabe) und Exception :)

**Comment by ChrisKujawa** [comment]
und jo Pfad is angepasst mach glei nen push

**Comment by mbaeten** [comment]
alles klar, danke ;D
