### ISSUE TITLE
BUG: ClassFile main not found

### ISSUE THREAD

**Issue by ChrisKujawa** [ccebinger/SWPSoSe14#65]
Wenn ich out.class ausfuehren will dann findet er die main net?

java out.class 
Error: Could not find or load main class out.class

**Comment by ChrisKujawa** [comment]
$ xxd out.class : 

0000000: cafe babe 0000 0033 0007 0010 6a61 7661  .......3....java
0000010: 2f6c 616e 672f 7379 7374 656d 0009 0014  /lang/system....
0000020: 6a61 7661 2e6c 616e 672e 7379 7374 656d  java.lang.system
0000030: 2e6f 7574 000a 001b 4a61 7661 2e69 6f2e  .out....Java.io.
0000040: 7072 696e 7453 7472 6561 6d2e 7072 696e  printStream.prin
0000050: 746c 6e00 0a00 094d 6169 6e2e 6a61 7661  tln....Main.java
0000060: 0001 0001 3200 0100 0131 0009 002a 6a61  ....2....1..._ja
0000070: 7661 2f6c 616e 672f 5379 7374 656d 2e6f  va/lang/System.o
0000080: 7574 3a4c 6a61 7661 2f69 6f2f 5072 696e  ut:Ljava/io/Prin
0000090: 7453 7472 6561 6d3b 000a 002f 6a61 7661  tStream;.../java
00000a0: 2f69 6f2f 5072 696e 7453 7472 6561 6d2e  /io/PrintStream.
00000b0: 7072 696e 743a 284c 6a61 7661 2f6c 616e  print:(Ljava/lan
00000c0: 672f 5374 7269 6e67 3b29 5600 0000 0137  g/String;)V....7
00000d0: 3738 3800 0000 0033 0001 0007 0008 0001  788....3........
00000e0: 0009 0000 001d 0001 0001 0000 0005 2ab7  .............._.
00000f0: 0001 b100 0000 0900 0b00 0c00 0100 0900  ................
0000100: 0000 2500 0200 0100 0000 09b2 0002 1203  ..%.............
0000110: b600 04b1 0000                           ......

**Comment by jdettlaff** [comment]
Richtige Nutzung des Java-Befehls:
java out

Das .class am Ende wird sonst als Teil des Klassennamens interpretiert und er sucht nach der Datei out.class.class ;)

**Comment by ChrisKujawa** [comment]
Stimmt hast recht sorry.

Aber dann bekomm ich diese Exception:

 java out
Exception in thread "main" java.lang.ClassFormatError: Truncated class file
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Liegts am Class format oder an unserem erzeugten Bytecode?

**Comment by jdettlaff** [comment]
Die generierte class-Datei ist offenbar ungültig und kaputt, mal mit javap disassemblen wenn ich zu Hause bin, ist ja schon an mich zugewiesen, danke.

**Comment by jdettlaff** [comment]
Problem bekannt, s. Ticket #46
